contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
staticDir = "static"
assetDir = "static"
buildDrafts = false
baseURL = "https://comic-cms.netlify.com"
canonifyURLs = true
title = "Tavern Wenches"
sectionPagesMenu = "main"
paginate = 10
paginatePath = "archive"
theme = "webcomic"

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[outputs]
  section = ["HTML", "RSS"]

[taxonomies]
#   tag = "tags"
#   category = "categories"

[params]
  author = "S Frisk"
  author_site = "http://www.sarahfrisk.com/"
  subtitle = "A Dungeon Not to Be Mastered"
  og_description = "A webcomic following the lives of the tavern wenches serving in an RPG campaign."
  og_image = "/assets/images/logo.jpg"
  og_site_name = "Tavern Wenches"
  twitter_site = "TavernWenches"
  twitter_creator = "SarahFrisk"
  twitter_image = ""
  og_type = "website"
  og_local = "en-US"
  facebook = "TavernWenches"
  # tumblr = ""
  twitter = "sarahfrisk"
  instagram = "friskycomics"
  # youtube = ""
  # twitch = ""
  patreon = "friskycomics"
  tapas = "https://tapas.io/series/Tavern-Wenches/info"
  webtoon = "https://www.webtoons.com/en/challenge/tavern-wenches/list?title_no=511037"